[package]
name = "st-terminal-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A small, fast, cross-platform terminal emulator inspired by st-terminal. Target < 3 MB."

[[bin]]
name = "st-terminal-rs"
path = "src/main.rs"

[dependencies]
font8x8 = "0.3.1"
softbuffer = "0.4.8"
winit = "0.30.13"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_Environment",
    "Win32_System_Memory",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
]
